# Generated by Django 4.0.4 on 2022-04-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_alter_fileupload_upload_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='upload_file',
            field=models.FileField(upload_to=''),
        ),
    ]
